version: 2.1
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Front-End Install
          command: |
            npm run front-end:install
      - run:
          name: Back-End Install
          command: |
            npm run back-end:install
      - run:
          name: Front-End Build
          command: |
            npm run front-end:build
      - run:
          name: Back-End Build
          command: |
            npm run back-end:build
      - run:
          name: Deploy UI
          command: |
            npm run front-end:deploy
      - run:
          name: Deploy Server
          command: |
            npm run back-end:deploy                  
workflows:
  build-deploy:
    jobs:
      steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - build:
          filters:
            branches:
              only: master